# Generated by Django 4.1.4 on 2023-01-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_adminprofileuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofileuser',
            name='image',
            field=models.ImageField(default='profilowe.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=2137),
        ),
    ]
