# Generated by Django 4.1.4 on 2023-01-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_adminprofileuser_image_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='playerID',
            field=models.CharField(default='0000', max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
