# Generated by Django 4.1.5 on 2023-01-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_loses_profile_playerid_profile_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofileuser',
            name='image',
            field=models.ImageField(default='profilowe.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profilowe.png', upload_to='profile_pics'),
        ),
    ]
