# Generated by Django 4.1.5 on 2023-01-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_adminprofileuser_image_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofileuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
