# Generated by Django 4.1.4 on 2023-01-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_statkiroom_trackplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackplayer',
            name='room',
        ),
        migrations.AddField(
            model_name='trackplayer',
            name='room_name',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
